apiVersion: v1
kind: ServiceAccount
metadata:
  name: diary-app-sa
  namespace: diary-app
  annotations:
    # Terraform으로 생성한 IAM Role ARN - S3 사용시 주석 제거
    eks.amazonaws.com/role-arn: arn:aws:iam::194722398200:role/team4-diary-app-irsa
