apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: diary-app-prod
  namespace: argocd # ArgoCD가 설치된 네임스페이스
spec:
  project: team4-project

  source:
    repoURL: https://github.com/CLD-05/team4_config.git
    targetRevision: main
    path: apps/diary-app/overlays/prod # prod overlay 경로 추적

  destination:
    server: https://kubernetes.default.svc
    namespace: diary-app-prod

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    # 운영 전환 시 아래 주석 해제
    automated:
      prune: true
      selfHeal: true
