apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: diary-app

# base를 그대로 상속
resources:
  - ../../base

# dev 환경 전용 패치 적용
patches:
  - path: patch-deployment.yaml
    target:
      kind: Deployment
      name: diary-app
