apiVersion: apps/v1
kind: Deployment
metadata:
  name: diary-app
  namespace: diary-app-dev
spec:
  replicas: 1 # dev는 1개로 절약
  template:
    spec:
      containers:
        - name: diary-app
          image: 194722398200.dkr.ecr.ap-northeast-2.amazonaws.com/team4-backend-api:33261df7bbac75a6e28f74687f8ba5f9df458296
          resources:
            requests:
              cpu: "250m" # dev는 낮은 사양
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
