apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: diary-app-prod

resources:
- ../../base

patches:
- path: patch-deployment.yaml
  target:
    kind: Deployment
    name: diary-app
images:
- name: 194722398200.dkr.ecr.ap-northeast-2.amazonaws.com/team4-backend-api
  newName: 194722398200.dkr.ecr.ap-northeast-2.amazonaws.com/team4-backend-api
  newTag: b5df7821841ecf9506bd8903dcc353718d8a6ddf
