apiVersion: apps/v1
kind: Deployment
metadata:
  name: diary-app
  namespace: diary-app-prod
spec:
  replicas: 2 # prod는 고가용성 2개 유지
  template:
    spec:
      containers:
        - name: diary-app
          image: 194722398200.dkr.ecr.ap-northeast-2.amazonaws.com/team4-backend-api:6757ae1c68c0bdb4de347bd24b5246dccd3b0e73
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
